### ISSUE TITLE
Plugin is not installed error

### ISSUE THREAD

**Issue by scamps86** [smartlook/cordova-smartlook#68]
I'm trying the new release 2.0.1 for this plugin, but it seems that it's not installing it properly in both Android and iOS.
If I use the 1.9.6 it works perfectly.

Also the documentation for @awesome-cordova-plugins/smartlook is wrong because the specified methods are different.

`[warn] - Native: tried calling Smartlook.setup, but the Smartlook plugin is not installed.
⚡️  [warn] - Install the Smartlook plugin: 'ionic cordova plugin add https://github.com/smartlook/cordova-smartlook.git'`

**Comment by kiwikia** [comment]
I'm also getting the same issue, what version of `@awesome-cordova-plugins/smartlook` are you using @scamps86 ?

**Comment by c0mtru1se** [comment]
Hey!
Sorry for the trouble, may I please ask when did you both follow the installation instructions? We had big issues with getting our `v2` changes merged into the `@awesome-cordova-plugins/smartlook` repository, but in the middle of July (18th, respectively), it was finally [released](https://www.npmjs.com/package/@awesome-cordova-plugins/smartlook) in version `6.4.0` of the repo.
I have then also cleaned up, fixed and updated our [docs](https://mobile.developer.smartlook.com/reference/ionic-sdk-installation) which should resolve in a successful installation, as well as integration snippets for `Angular`, `Vue` or `React`. Could you please check whether you followed the new instructions, and install from the updated oss package?
Thx for the info!

**Comment by kiwikia** [comment]
Hi @c0mtru1se thanks yes the latest version of @awesome-cordova-plugins/smartlook solved the above issue for me. 

I am now getting a crash when launching with an error `DYLD error: Library not loaded: @rpath/SmartlookAnalytics.framework/SmartlookAnalytics` 

Should I raise a new issue for this? (unsure if it's related).

**Comment by dksanket** [comment]
I am getting " Native: tried calling Smartlook.startRecording, but the Smartlook plugin is not installed." in android, and "Native: tried calling Smartlook.setUserIdentifier, but Cordova is not available. Make sure to include cordova.js or run in a device/simulator" in web. Could you please help me with it.

"@awesome-cordova-plugins/smartlook": "^5.46.0",
 "cordova-plugin-smartlook": "^2.0.1",
Angular 11, ionic 5, capacitor 3

**Comment by c0mtru1se** [comment]
@dksanket thanks, please update the `@awesome-cordova-plugins/smartlook` package to the latest version `6.4.0` and let me know, the issue should be resolved.
Also, you can update our `cordova-plugin-smartlook` to a new version, `2.0.2` which comes fix some arbitrary bug fixes.

Thanks!

**Comment by dksanket** [comment]
@c0mtru1se thank you for the quick response, I tried it but the issue still exists. I am getting the following warning in the console "common.js:350 Native: tried calling Smartlook.setup, but Cordova is not available. Make sure to include cordova.js or run in a device/simulator" in web. Haven't tried it in android yet. However, I thought @awesome-cordova-plugins versions 6 and above support only angular 12 and above, whereas our project is in angular 11.

**Comment by c0mtru1se** [comment]
@dksanket I see, I'm assuming you are testing the app with either `ionic serve` or `ionic cordova run browser`?
That will, unfortunately, not work as this package **does not** support the `browser` platform. It contains the native mobile SDKs only, e.g. `Android` and `iOS` ones.
Please, test the package only by running on Android or iOS si/emulators or devices.

Ad `@awesome-cordova-plugins` - the problem is that anything bellow `v6` does not support our v2 SDK API, hence the _"Native: tried calling Smartlook.startRecording, but the Smartlook plugin is not installed."_ error you already reported.

**Comment by scamps86** [comment]
@kiwikia Finally I've fixed it by using the following:

`@awesome-cordova-plugins/smartlook` -> 6.3.0 
`cordova-plugin-smartlook` -> 1.9.6

this works in iOS, but not in Android. To get it working on Android I've modified `node_modules/cordova-plugin-smartlook/src/android/plugin.gradle` with the following:

`repositories {
    maven {
      url "https://sdk.smartlook.com/android/release"
    }
}

dependencies {
    implementation 'com.smartlook.recording:app:1.8.13-cordova'
}
`

**Comment by dksanket** [comment]
It's not working for me, could you please tell me the versions that you are using? I am using angular 11, ionic 5, capacitor 3.. I even tried with "@awesome-cordova-plugins/smartlook": "^5.46.0" and cordova-plugin-smartlook -> 1.9.6, didn't work.
